name: Mise à jour automatique du Portail

on:
  # 1. Se lance à chaque fois que tu fais un "git push" sur la branche main
  push:
    branches:
      - main
  
  # 2. Se lance toutes les 30 minutes
  schedule:
    - cron: '*/30 * * * *'
  
  # 3. Permet de lancer le déploiement manuellement
  workflow_dispatch: 

# Permissions nécessaires pour déployer sur GitHub Pages via les Actions
permissions:
  contents: read
  pages: write
  id-token: write

# Permet d'annuler un déploiement en cours si un nouveau est lancé
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installation des dépendances
        run: |
          pip install mkdocs-material mkdocs-macros-plugin

      # On remplace "gh-deploy" par "build" : on construit juste les fichiers dans le dossier "site/"
      - name: Construction du site MkDocs
        run: |
          mkdocs build

      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v4

      # Cette action prend le dossier "site/" et le prépare pour l'envoi
      - name: Upload de l'artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

  # Nouveau Job qui s'occupe uniquement de la mise en ligne
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Déploiement sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4